package com.govind_space;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class ResultFromApiDO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "refreshToken")
	private java.lang.String refreshToken;

	@org.kie.api.definition.type.Label(value = "accessToken")
	private java.lang.String accessToken;

	public ResultFromApiDO() {
	}

	public java.lang.String getRefreshToken() {
		return this.refreshToken;
	}

	public void setRefreshToken(java.lang.String refreshToken) {
		this.refreshToken = refreshToken;
	}

	public java.lang.String getAccessToken() {
		return this.accessToken;
	}

	public void setAccessToken(java.lang.String accessToken) {
		this.accessToken = accessToken;
	}

	public ResultFromApiDO(java.lang.String refreshToken,
			java.lang.String accessToken) {
		this.refreshToken = refreshToken;
		this.accessToken = accessToken;
	}

}