package com.govind_space.receipt_creation;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Applicant implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Age")
	private Integer age;
	@org.kie.api.definition.type.Label("Is_Existing_Customer")
	private boolean existingCustomer;

	@org.kie.api.definition.type.Label("DemoGraphic_Assessment")
	private java.lang.String demographicAssessment;

	public Applicant() {
	}

	public java.lang.String getDemographicAssessment() {
		return this.demographicAssessment;
	}

	public void setDemographicAssessment(java.lang.String demographicAssessment) {
		this.demographicAssessment = demographicAssessment;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public boolean isExistingCustomer() {
		return this.existingCustomer;
	}

	public void setExistingCustomer(boolean existingCustomer) {
		this.existingCustomer = existingCustomer;
	}

	public Applicant(java.lang.Integer age, boolean existingCustomer,
			java.lang.String demographicAssessment) {
		this.age = age;
		this.existingCustomer = existingCustomer;
		this.demographicAssessment = demographicAssessment;
	}

}