package com.govind_space.receipt_creation;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LoanApplicantDO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "age")
	private java.lang.Integer age;
	@org.kie.api.definition.type.Label(value = "status")
	private java.lang.String status;

	public LoanApplicantDO() {
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public LoanApplicantDO(java.lang.Integer age, java.lang.String status) {
		this.age = age;
		this.status = status;
	}

}